In [1]:
from lib import twoatoms
import numpy as np

In [2]:
atom = twoatoms.single_atom(power_blue=0.73e-3, waste_blue=90e-6, power_IR=20e-3, waste_IR=130e-6, detuning_blue=100)

In [3]:
atom.two_photon_rabi_freq
atom.Gamma_6p

8.464336735423064

In [6]:
rho0 = np.zeros([4,4])
rho0[0,0] = 1
res = atom.evolve(time=10, steps=100000, initial_DM=rho0)

In [8]:
res.states

[Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
 Qobj data =
 [[1. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]],
 Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
 Qobj data =
 [[ 9.99999569e-01+0.00000000e+00j  3.28375431e-06+6.56789834e-04j
   -2.60861924e-08+8.79032218e-11j -4.68294938e-10-1.38973985e-07j]
  [ 3.28375431e-06-6.56789834e-04j  4.31380141e-07+0.00000000e+00j
   -4.40326532e-14+1.73201777e-11j -9.22664149e-11-2.34580304e-13j]
  [-2.60861924e-08-8.79032218e-11j -4.40326532e-14-1.73201777e-11j
    1.04934843e-15+0.00000000e+00j  5.50479648e-23+5.59060868e-15j]
  [-4.68294938e-10+1.38973985e-07j -9.22664149e-11+2.34580304e-13j
    5.50479648e-23-5.59060868e-15j  2.97850592e-14+0.00000000e+00j]],
 Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
 Qobj data =
 [[ 9.99998275e-01+0.00000000e+00j  1.31310105e-05+1.31323522e-03j
   -1.04327493e-07+6.96370909e-10j -3.70955445e-0